### ISSUE TITLE
[BUG] 图与其后的文字距离是论文格式要求还是bug？

### ISSUE THREAD

**Issue by CarlDegio** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#100]
**描述您的问题 (Describe the bug)**

发现编译出来的论文与下方的文字有些距离，大约一行，请问是论文格式要求还是编译时的bug？

**环境与版本信息**
1. 代码版本(Code version)（留空则默认最新）：
2. 操作系统 (OS)：Windows
3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：texlive2022
4. Tex 编译器 (Tex compiler, eg. XeTeX): xetex

**错误内容 (Error contents)**

![image](https://user-images.githubusercontent.com/52379582/236777675-2f04276a-2beb-47a7-9b6a-06af1a891a9d.png)

在样例版本里面也发现了该情况：

![image](https://user-images.githubusercontent.com/52379582/236777473-bc0e3a62-c85e-4cde-a9c0-2fe7b8697ba6.png)

**可复现内容 (Reproduceable steps)**
正常编译时就存在

**Comment by note286** [comment]
起码挨着不美观。

**Comment by CarlDegio** [comment]
彳亍

**Comment by polossk** [comment]
其实是LaTeX的排版特性，因为都是浮动体，即使设置了宽度（即便是强制硬宽度），浮动体外围同样会有一个弹簧长度的空白区域。
