### ISSUE TITLE
[BUG] 参考文献格式的问题

### ISSUE THREAD

**Issue by CarlDegio** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#101]
**描述您的问题 (Describe the bug)**

参考文献格式似乎有问题，比如bib中提供了url时，页面中会加入url，但按GB/T 7714-2015标准，貌似是不应该出现链接的。以及对于arxiv引用的论文，产生的格式也有问题。

下图中不应当出现url
![image](https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/assets/52379582/ede65b4c-4aef-42ff-9cf1-af2541ee86e6)

arxiv文献的问题，一是类型[Z]，这个可以通过手动改为article类型修改，二是没有出现编号。
![image](https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/assets/52379582/cf18a199-d0fa-4456-8eb1-bbfaf24c7cd9)
谷歌学术中给出的标准版本如下：
![image](https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/assets/52379582/8e5c8afd-a0f5-4acf-9745-05a7ff81e367)

**环境与版本信息**
1. 代码版本(Code version)（留空则默认最新）：
2. 操作系统 (OS)：windows
3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：2022
4. Tex 编译器 (Tex compiler, eg. XeTeX): xetex

**错误内容 (Error contents)**

*如果您能提供错误信息（比如编译器），请在此粘贴 (Provide the error information if you could)*

**可复现内容 (Reproduceable steps)**

*请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段 (Describe your current behavior and code to reproduce the issue)*

** 附加内容 (Other info, bugs and logs)**

*如果您对于此BUG有何见解或者有一些附加信息，请在此键入(Tell us your hints and thought about the bug)*

**Comment by note286** [comment]
关于arxiv参考 https://github.com/zepinglee/gbt7714-bibtex-style/issues/89 。

关于链接，在专著中的析出文献，可以添加获取和访问路径，也就是链接。如果你不想要，你可以在`.bib`中移除。
