### ISSUE TITLE
封面页顶部没有学校代码、学号等等信息

### ISSUE THREAD

**Issue by desperadoshi** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#16]
如题
这种表现与学校14年的论文编写规则不符吧？

**Comment by polossk** [comment]
您好！
我们已经定位问题，正在处理，请您稍安勿躁。

**Comment by polossk** [comment]
@desperadoshi 您好，由于另外两个同学这几天比较忙还没来得及review代码，如果您着急的话，可以进 coverpage 分支下载使用带有外封皮的版本。
附地址：https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/tree/coverpage

**Comment by desperadoshi** [comment]
> @desperadoshi 您好，由于另外两个同学这几天比较忙还没来得及review代码，如果您着急的话，可以进 coverpage 分支下载使用带有外封皮的版本。
> 附地址：https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/tree/coverpage

非常感谢！我不着急。感谢各位的工作！

**Comment by polossk** [comment]
#17 已更新，请直接在 master 分支下下载最新版本使用
