### ISSUE TITLE
mac版本字体问题

### ISSUE THREAD

**Issue by ZERO2ER0** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#20]
作者您好：
这个模版是不是没有考虑mac os的兼容问题。我编译过程遇到字体问题。对于字体选择这块我不是很懂，如果我自己想操作的话，是不是需要自己把字体拷贝过来。然后具体改thesis-setting的哪一块，谢谢您！

**Comment by kidozh** [comment]
您好：

  字体这一块因为版权问题，项目里面不提供下载链接，您需要自己下载相应的字体的（应该是楷体，宋体这一类，您可以在thesis-setting.tex中看到相应的字体）。因为开发者们好像都没有Mac设备，所以暂时无法复现这个问题。但是综合您的陈述，应该安装上字体就应该能解决字体报错的问题。

PS，您可以附上错误信息以便我们更好的定位和解决问题。

**Comment by ZERO2ER0** [comment]
> 您好：
> 
> 字体这一块因为版权问题，项目里面不提供下载链接，您需要自己下载相应的字体的（应该是楷体，宋体这一类，您可以在thesis-setting.tex中看到相应的字体）。因为开发者们好像都没有Mac设备，所以暂时无法复现这个问题。但是综合您的陈述，应该安装上字体就应该能解决字体报错的问题。
> 
> PS，您可以附上错误信息以便我们更好的定位和解决问题。

mac版本的问题，我这周有空尝试下将字体拷过来，感谢作者大佬！！！

**Comment by ZERO2ER0** [comment]
> 您好：
> 
> 字体这一块因为版权问题，项目里面不提供下载链接，您需要自己下载相应的字体的（应该是楷体，宋体这一类，您可以在thesis-setting.tex中看到相应的字体）。因为开发者们好像都没有Mac设备，所以暂时无法复现这个问题。但是综合您的陈述，应该安装上字体就应该能解决字体报错的问题。
> 
> PS，您可以附上错误信息以便我们更好的定位和解决问题。

首先感谢作者的辛勤工作，对于Mac版本的字体问题，今天进行了测试。
需要将thesis-setting.tex中字体设置部分改为
`\newcommand\defaultSog{SimSong}
\newcommand\defaultHei{Heiti SC}
\newcommand\defaultKai{Kaiti SC}
\newcommand\defaultFag{STFangSong}
\newcommand\defaultEngFont{Times New Roman}
\newcommand\codeFont{Consolas}`

并从[https://gist.github.com/nmcc/4e8ead6c380d8331fedd04e1aa41d351](url)下载Consolas字体文件进行安装。

**Comment by kidozh** [comment]
我们会跟进这个问题，可能会在注释或者README.MD中提到如何解决这个问题。非常感谢你的测试。
