### ISSUE TITLE
Win版本中文参考文献

### ISSUE THREAD

**Issue by ZERO2ER0** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#21]
作者您好：
我添加中文参考文献报错，请问这个支持中文参考文献吗。谢谢～

**Comment by kidozh** [comment]
您好：

  应该是支持中文参考文献的。请问您装的是tex live吗？还有报错信息能否提供一下以便我们更好的确定问题所在？

**Comment by kidozh** [comment]
您好：

  经过我们在本地的复现，我们顺利的编译出了带中文的参考文献
![image](https://user-images.githubusercontent.com/11661760/98958890-b7b11280-253d-11eb-9f63-86b380d918dc.png)

  我们的Tex代码应当是支持中文参考文献的，我们在此给出我们的测试环境，供您参考：
1. 代码版本(Code version)：最新版本
2. 操作系统 (OS)：Windows 10
3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：Tex Live 2020
4. Tex 编译器 (Tex compiler, eg. XeTeX):  XeLaTeX - BibTex - XeLaTeX - XeLaTex

  你也可以提供更多的详细信息帮助定位问题所在。

**Comment by ZERO2ER0** [comment]
> 您好：
> 
> 经过我们在本地的复现，我们顺利的编译出了带中文的参考文献
> ![image](https://user-images.githubusercontent.com/11661760/98958890-b7b11280-253d-11eb-9f63-86b380d918dc.png)
> 
> 我们的Tex代码应当是支持中文参考文献的，我们在此给出我们的测试环境，供您参考：
> 
> 1. 代码版本(Code version)：最新版本
> 2. 操作系统 (OS)：Windows 10
> 3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：Tex Live 2020
> 4. Tex 编译器 (Tex compiler, eg. XeTeX):  XeLaTeX - BibTex - XeLaTeX - XeLaTex
> 
> 你也可以提供更多的详细信息帮助定位问题所在。

十分感谢作者大佬回复，WIN10系统下，TexLive和Tex编译器，代码版本与您是一致的。目前出问题的那台win电脑没在跟前，周末应该有机会，我再去尝试复现下问题。再次感谢！！！

**Comment by kidozh** [comment]
Closed with no further reply.

You can still reopen this issue to report this bug. Thanks for your issue.
