### ISSUE TITLE
[BUG] 中文姓名在英文版封面显示为方框

### ISSUE THREAD

**Issue by desperadoshi** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#22]
**描述您的问题 (Describe the bug)**

中文姓名在英文版封面显示为方框

**环境与版本信息**
1. 代码版本(Code version)（留空则默认最新）：master分支最新版本6118d50
2. 操作系统 (OS)：overleaf
3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：overleaf-TexLive 2019
4. Tex 编译器 (Tex compiler, eg. XeTeX): XeLaTeX

**可复现内容 (Reproduceable steps)**

`document.tex`中`\authorname`使用中文姓名。
`frontpage_eng.tex`会在作者一栏显示方框。

**可能的解决方案 (Possible fix)**

Add a new defined command: `\newcommand{\authornameeng}{SomeBody}` and let `frontpage_eng.tex` use `\authornameeng`.

**Comment by kidozh** [comment]
感谢您的建议，已按照您的建议修复了这个问题。
