### ISSUE TITLE
[Suggestion] Check out a new branch working for Overleaf

### ISSUE THREAD

**Issue by desperadoshi** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#23]
在留下您的建议时，辛苦您同步提供如下信息：
1. 代码版本(Code version)（留空则默认最新）：master分支最新版本
2. 操作系统 (OS)：Overleaf
3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：2020
4. Tex 编译器 (Tex compiler, eg. XeTeX): XeLaTex

**你的建议是否和一个已知问题有关 (Is your feature request related to a problem? Please describe.)**
No

**告诉我们你想要的解决方案(Describe the solution you'd like)**
Checkout a new branch, for example, whose name is overleaf. Do some necessary changes to make it work for Overleaf. Keep the style same as that produced by a local TeX system on a local machine.

Overleaf is really a good platform widely used by researchers. I believe that a lot of Ph.D. candidates are using it to draft their thesis. The necessary changes should be minimal. For example, in order to use FangSong, you need to set `\newcommand\defaultSog{simsun.ttc}` with the font file `simsun.ttc` uploaded to Overleaf. The `master` branch now is `\newcommand\defaultSog{SimSun}`. Overleaf does not understand what `SimSun` is.

**告诉我们你想到的其他替代方案(Describe alternatives you've considered)**
简介而精准的告诉我们其他替代方案 (A clear and concise description of any alternative solutions or features you've considered.)

Of course, if you choose not to provide such a solution for Overleaf users, they could make their own changes to adapt to Overleaf. That is OK.

I do think Overleaf version is necessary. And it is not hard.

**其他信息(Additional context)**
添加有关这个建议的其他信息，例如截图(Add any other context or screenshots about the feature request here.)

**Comment by polossk** [comment]
我们可能不会额外新开 overleaf 分支，但是可能会把一些必要的更改通过注释的方式添加进配置文件中。主要原因是在保证核心代码不变的前提下同时维护两个分支的是一件很麻烦的事情。也希望您能理解。
我们会尽快完善这一模板。感谢您的使用和热心反馈。

**Comment by kidozh** [comment]
我仔细看了一下StackOverflow上关于中文的解释，好像都是使用\setCJKmainfont{SimSun}就可以正常使用宋体。

[https://tex.stackexchange.com/questions/17611/how-does-one-type-chinese-in-latex](https://tex.stackexchange.com/questions/17611/how-does-one-type-chinese-in-latex)

我尝试在overleaf上运行此项目，但似乎报了一个超时错误。因此也没有办法查证关于overleaf的BUG（同#24）

我们可能需要进一步的信息。

**Comment by polossk** [comment]
Closed due to no more comment.
