### ISSUE TITLE
[BUG] 英文封面部分内容没有按要求加粗

### ISSUE THREAD

**Issue by desperadoshi** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#24]
**描述您的问题 (Describe the bug)**

Overleaf下英文封面部分没有加粗。

**环境与版本信息**
1. 代码版本(Code version)（留空则默认最新）：master-6118d50
2. 操作系统 (OS)：Overleaf
3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：2019
4. Tex 编译器 (Tex compiler, eg. XeTeX): XeLaTeX

**错误内容 (Error contents)**

Overleaf下英文封面部分没有加粗。

**可复现内容 (Reproduceable steps)**

`fontpage_eng.tex`中重复定义了`\setmainfont{\defaultEngFont}`。在Overleaf中，为了使英文可加粗，需要修改`thesis-setting.tex`中`\setmainfont{\defaultEngFont}`为`\setmainfont[BoldFont=timesbd.ttf]{\defaultEngFont}`以使用上传到Overleaf的粗体罗马英文字体。`frontpage_eng.tex`中重复定义了`\defaultEngFont`，故覆盖了全局设定，造成英文封面无法加粗英文。

可能的解决方案：`frontpage_eng.tex`中注释掉相关部分。

**Comment by polossk** [comment]
石博士您好！
我们注意到了这个问题，包括 #22 #23 ，我们会优先修复两个 BUG（本 issue 和 #22 ），然后可能会发布一个适配 Overleaf 的版本。实际上，本小组内的成员均是使用本地的 texlive 进行文档编辑，可能没有考虑到在线编译版本的情形，这里也希望您能理解。
您可以优先处理文档内容，等待配置文件的更新。
感谢您的使用及热心反馈！

**Comment by kidozh** [comment]
我们替换掉字体为Noto Sans CJK SC后，尝试在overleaf上编译pdf，我们并未重现此BUG。

![image](https://user-images.githubusercontent.com/11661760/99698676-04f82b80-2acc-11eb-9add-d87841707a9f.png)

[此尝试Overleaf项目](https://www.overleaf.com/project/5fb6a00f8fe57d6c5c0bc106)

**Comment by desperadoshi** [comment]
> 我们替换掉字体为Noto Sans CJK SC后，尝试在overleaf上编译pdf，我们并未重现此BUG。
> 
> ![image](https://user-images.githubusercontent.com/11661760/99698676-04f82b80-2acc-11eb-9add-d87841707a9f.png)
> 
> [此尝试Overleaf项目](https://www.overleaf.com/project/5fb6a00f8fe57d6c5c0bc106)

你好！我采用的是默认的中文宋体，英文Times New Roman。我认为不应该尝试使用其他字体，毕竟我校的论文排版要求使用这些字体。换用Noto Sans CJK SC字体后，论文排版是否合乎要求存疑。

**Comment by polossk** [comment]
您好，根据 Overleaf 文档关于预安装字体的信息[1]，黑体（或 Sans 字体，无衬线字体）可以选用 Noto Sans CJK SC，宋体（或Sans Serif 字体，衬线字体）可以选用 Noto Sans Serif CJK SC。Noto CJK[2] 是谷歌开发的一套公共字体库。

所以你说的黑体问题，恰好是因为我们更换到了黑体字体而已。

ref: 
1. **Which OTF or TTF fonts are supported via fontspec? - Overleaf, Online LaTeX Editor** <https://www.overleaf.com/learn/latex/Questions/Which%20OTF%20or%20TTF%20fonts%20are%20supported%20via%20fontspec%3F#Chinese>
2. Noto CJK – Google Noto Fonts <https://www.google.com/get/noto/help/cjk/>

**Comment by desperadoshi** [comment]
> 您好，根据 Overleaf 文档关于预安装字体的信息[1]，黑体（或 Sans 字体，无衬线字体）可以选用 Noto Sans CJK SC，宋体（或Sans Serif 字体，衬线字体）可以选用 Noto Sans Serif CJK SC。Noto CJK[2] 是谷歌开发的一套公共字体库。
> 
> 所以你说的黑体问题，恰好是因为我们更换到了黑体字体而已。
> 
> ref:
> 
> 1. **Which OTF or TTF fonts are supported via fontspec? - Overleaf, Online LaTeX Editor** https://www.overleaf.com/learn/latex/Questions/Which%20OTF%20or%20TTF%20fonts%20are%20supported%20via%20fontspec%3F#Chinese
> 2. **Noto CJK – Google Noto Fonts** https://www.google.com/get/noto/help/cjk/

我的意思是采用Noto Sans SJC SC没有严格遵守学校的字体要求。实现一个完全合乎学校排版要求的LaTeX版本论文模板应该是repo的首要目的。

另外，Windows平台下使用SimHei字体，Overleaf平台下却使用了Noto Sans CJK SC字体，这会带来不一致。我认为应该在注释里写明，用户自行上传字体至Overleaf的项目目录下，然后修改SimHei为simhei.ttf，Times New Roman为times.ttf。

**Comment by polossk** [comment]
SimHei 字体是有版权的，很抱歉我们无法提供。

**Comment by desperadoshi** [comment]
我知道SimHei是有版权的，注释里让用户自己上传即可。我们现在讨论的是本repo的代码能否得到学校要求的排版样式问题。

**Comment by polossk** [comment]
就目前来看，模板的样式是符合要求的。问题的根源出在使用在线平台编译而非本模板所说的 Windows 下 texlive 版本编译。

**Comment by polossk** [comment]
我们了解不同的用户有不同的使用习惯、使用方式，但是我们小组内的在读学生们不可能把所有人的想法、习惯、要求都汇总到一个万能模板上。更何况我们的初衷是在于把已有的工作公开以方便后人少走弯路或者直接使用。请您注意，不是学校要求必须使用 XX 模板，也不是我们做这个模板有收益有利益。我们只是单纯的把自己环境下能跑通的结果，去掉隐私信息后，发布上网，仅此而已。

我们了解到任何人都可以提出批评建议和自己的需求，但是不代表我们每一个建议和需求都会完成。我们也了解到您在 LaTeX 的使用上比我们更有经验，所以我们欢迎您贡献关于如何使用在线编译器版本下的相关代码、解决方案、及配套的使用说明。如果您觉得工作量超越了本 repo 的价值，也可以独立形成自己的 repo。无论是何种方式，最终都能解决问题，我们对此均表示欢迎。

**Comment by polossk** [comment]
No more comment. Close.
