### ISSUE TITLE
[BUG] 中文封面“题目”二字应为一号大小

### ISSUE THREAD

**Issue by desperadoshi** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#25]
**描述您的问题 (Describe the bug)**

中文封面“题目”二字应为一号大小

**环境与版本信息**
1. 代码版本(Code version)（留空则默认最新）：master-6118d50
2. 操作系统 (OS)：Overleaf
3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：Overleaf-2019
4. Tex 编译器 (Tex compiler, eg. XeTeX): XeLaTeX

**错误内容 (Error contents)**

根据[西北工业大学博士研究生学位论文编写规则（试用版）](http://gs.nwpu.edu.cn/info/1143/1139.htm)，中文封面“题目”二字字号应为26，即一号。

当前版本为二号大小。

**Comment by polossk** [comment]
欢迎 PR 贡献代码
