### ISSUE TITLE
中文摘要后没有空白页[BUG]

### ISSUE THREAD

**Issue by likunyao** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#27]
**描述您的问题 (Describe the bug)**

*简洁、精准的概括您的问题（A clear and concise description of what the bug is.）例如：“在Mac OS系统下使用Tex Live 2019编译失败”*

**环境与版本信息**
1. 代码版本(Code version)（留空则默认最新）：
2. 操作系统 (OS)：
3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：
4. Tex 编译器 (Tex compiler, eg. XeTeX): 

**错误内容 (Error contents)**

*如果您能提供错误信息（比如编译器），请在此粘贴 (Provide the error information if you could)*

**可复现内容 (Reproduceable steps)**

*请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段 (Describe your current behavior and code to reproduce the issue)*

** 附加内容 (Other info, bugs and logs)**

*如果您对于此BUG有何见解或者有一些附加信息，请在此键入(Tell us your hints and thought about the bug)*

**Comment by kidozh** [comment]
Resolved in commit https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/commit/8bcc490578020c9cd7304a882b042bc67b83256a
