### ISSUE TITLE
格式修改

### ISSUE THREAD

**Issue by justforlearnso** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#28]
章节标题应该为“第一章”，而不是罗马数字

**Comment by polossk** [comment]
预计中午修复

**Comment by polossk** [comment]
您好！
我们查阅了 2014 年西北工业大学研究生院编写的西北工业大学博士研究生学位论文编写规则（试用版）。章节标题符合标准及所附示例，故不再修复。

> 2.6 目录页：按本规则3.2 论文组成部分及结构要求之第2—10项编目；以论文章节号3级编写（1 引言，1.1， 1.1.1..）。

**Comment by justforlearnso** [comment]
你好，
&nbsp; &nbsp; &nbsp; 谢谢，我没有注意查看论文模板，查阅以往师兄的论文中发现是以“第一章”的章标题开始的，以上。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 上午10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis] 格式修改 (#28)





 
您好！
 我们查阅了 2014 年西北工业大学研究生院编写的西北工业大学博士研究生学位论文编写规则（试用版）。章节标题符合标准及所附示例，故不再修复。
  
2.6 目录页：按本规则3.2 论文组成部分及结构要求之第2—10项编目；以论文章节号3级编写（1 引言，1.1， 1.1.1..）。

**Comment by polossk** [comment]
如果有其他格式问题，欢迎另开issue提问
