### ISSUE TITLE
Abstract page header is  not correct

### ISSUE THREAD

**Issue by y973970100** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#30]
In your template:
![image](https://user-images.githubusercontent.com/30524390/132272939-d850d554-3b81-43be-a02b-67596b5db4d4.png)
In the Standers:
![image](https://user-images.githubusercontent.com/30524390/132273209-68b535b8-dabf-4b40-9a38-c635f50ed14b.png)

And it will be much more thanks if a brief introduction for phd and master thesis change is provided ! 

And Thanks for all your works. It's very useful for me. Thanks you!

Best regard!

**Comment by polossk** [comment]
We'll handle this issue ASAP.

**Comment by cfrpg** [comment]
This bug is already fixed. You can temporarily download the master branch for the fix. We will update the release ve
