### ISSUE TITLE
[BUG] Reference is not correct

### ISSUE THREAD

**Issue by y973970100** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#31]
In your method:
![image](https://user-images.githubusercontent.com/30524390/132285281-72199709-1d92-431f-8ca9-c80bb32a1c89.png)

In the Standard:
![image](https://user-images.githubusercontent.com/30524390/132284743-ed5fadb8-cf7b-4a9d-af99-4b87032b40ab.png)
![image](https://user-images.githubusercontent.com/30524390/132285296-58a09953-f6ce-463c-aeb3-32a09cfdbf3b.png)

Hello developer : I found a few bugs in reference:
Journal（in bibtex：article） and Phd thesis（in bibtex：phdthesis） is very important for fix，but 学位论文thesis\会议论文conference paper\专利pattern\研究报告research paper\专著book requires a location in the reference which is not support in bibtex, which can be avoid as ref the author's paper.

So my only request is fit the journal's reference in standard:
1. et al should have a comma in the frount.
2. there have a space
![image](https://user-images.githubusercontent.com/30524390/132285600-eb8665a6-3362-4cd6-ae25-98ab078d3524.png)
3. That's all! Thanks！

I give you my reference:

@article{sajadi20193d,
  title={3D printed tubulanes as lightweight hypervelocity impact resistant structures},
  author={Sajadi, Seyed Mohammad and Woellner, Cristiano F and Ramesh, Prathyush and Eichmann, Shannon L and Sun, Qiushi and Boul, Peter J and Thaemlitz, Carl J and Rahman, Muhammad M and Baughman, Ray H and Galv{\~a}o, Douglas S and others},
  journal={Small},
  volume={15},
  number={52},
  pages={1904747},
  year={2019},
  publisher={Wiley Online Library}
}
@article{cai2020adaptive,
  title={An adaptive bubble method for structural shape and topology optimization},
  author={Cai, Shouyu and Zhang, Weihong and Yang, Chen},
  journal={Computer Methods in Applied Mechanics and Engineering},
  volume={360},
  number={52},
  pages={112778},
  year={2020},
  publisher={Elsevier}
}

**Comment by kidozh** [comment]
Hello y973970100,

  I am pleased to answer your question one by one.

   For the very beginning question, do you mean that the bibtex doesn't support the article types you mentioned? If you means that, we are sorry that we could not offer any suggestions to you since the members are kind of busy in their study and it's very less likely to port the reference style using biber which is estimated to take very long time.
  
  We have upload a patch adding a comma in front of the `et al.` to fix the first bug you just mentioned. However, we could not understand your second request which refers to a missing blank. Does it go behind the publisher or the year?

  All of our members can speak Mandarin by the way.

  Thanks for your report.

**Comment by y973970100** [comment]
Thanks for your continues improvement, kidozh!
I know the first question a quiet annoying and for the most of the latex tamplet isn't do support all of the article type, and which is not the issue I'm going to pull up. 
My suggestion is to fix the common issue to make a better experience for the people in the future. Some small bug I can handle but I perfer to submit for a great path for all of us using this project.
Now I answer the second quesiton, which I make the confuse.
Yes, I need a space in： 卷号(期号):**"Space"**页码
No other requires.
In this way the article type is fixed correct. Thanks all.
ps: You are so kind. LOL.

**Comment by polossk** [comment]
Hi, thanks for your suggestion.

It is fixed, wait for updating.

**Comment by y973970100** [comment]
no other questions you can close it. Thanks！

**Comment by polossk** [comment]
try https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/releases/tag/v1.5.3
@y973970100

**Comment by y973970100** [comment]
Hi I download the new release，I found the extra comma.
![image](https://user-images.githubusercontent.com/30524390/132469469-64bd257d-7acb-43a1-8ca8-f2cf1558a520.png)

I found the 图目录和表目录 , which is great but I don't know if that's ok in audit or review?

**Comment by y973970100** [comment]
![image](https://user-images.githubusercontent.com/30524390/132470260-e8035f0a-95fa-4865-a616-582a84c4b5a2.png)
正文行距稍微大一些，1.5倍，中间横线请稍微下调一些，谢谢~辛苦啦!

**Comment by y973970100** [comment]
还有两处错误：
1：大标题处应为两个空格，小标题应有一个空格：
![image](https://user-images.githubusercontent.com/30524390/132471106-91785650-7f76-4e6e-846d-ead7757277c8.png)
大标题明显间隙过大，小标题目测没啥问题
![image](https://user-images.githubusercontent.com/30524390/132471126-b2396899-64b4-42ae-85bd-9099f8676dcc.png)

2：引用错误typo，latex文中多一个冒号，请删除即可，没啥大碍
![image](https://user-images.githubusercontent.com/30524390/132470941-f44e9ba1-513d-4a44-929b-c50d97c4b9ec.png)

**Comment by polossk** [comment]
Hey! I'll talk about these requests one by one.

1. You'd better clean the temporary files, such as the *.aux, *.bbl, etc. Try `make clean` in your console if you have the `make` environment. Or open your console, then paste `del /s /f *.aux *.bbl *.blg *.log *.out *.gz *.toc *.thm *.fdb_latexmk *.fls *.acn *.glo *.ist` to make your working dictionary clean.
2. Someone wants the contents of figures and tables, so we add them to our template. They are not the necessary part of your dissertation.
3. The statement page is an auxiliary page of the dissertation. We don't find any clause in the standard that requires a page number on this page.
4. The separating line of the statement page will adjust in the coming commit.
5. The format of Primary headings only demands the details of the fonts, the size, and the paragraph spacing. Won't fix.
6. The typo error will fix in the coming commit.

Thank you for your thorough review. Have a good day!

**Comment by polossk** [comment]
try this https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/tree/polossk-dev

**Comment by y973970100** [comment]
> try this https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/tree/polossk-dev

That work in double comma, pls solve segment spacing.
Have a nice day~

**Comment by polossk** [comment]
https://raw.githubusercontent.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/polossk-dev/preview/references.png

**Comment by polossk** [comment]
fixed.
