### ISSUE TITLE
[Suggestion] 最后一页奇数页放置原创性声明

### ISSUE THREAD

**Issue by y973970100** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#32]
无页眉，放置页码，奇数页实现
![image](https://user-images.githubusercontent.com/30524390/132311281-5409f910-a327-4cf8-b9b5-68c0002d4105.png)
谢谢~

**Comment by cfrpg** [comment]
目前master版本已经加入了知识产权声明书，我们会尽快更新发布版.
