### ISSUE TITLE
[BUG]TexLive 2021下xelatex编译报错" LaTeX Error: Command \CJKglue already defined"

### ISSUE THREAD

**Issue by LuckySquirrel** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#39]
使用最新的1.5.3模板，在win10下使用texlive2021编译时出错。

`! LaTeX Error: Command \CJKglue already defined.
               Or name \end... illegal, see p.192 of the manual.`

尝试参考["CJKnumb 不再可用"](https://github.com/CTeX-org/ctex-kit/issues/562)，似乎是xeCJK与CJKnumb产生了冲突。做了以下尝试：

1. 将settings/thesis-setting设置中文字体的\usepackage{CJKnumb}更换为\RequirePackage{CJKnumb}错误依然存在；
2. 将\usepackage{CJKnumb}注释后，xelatex可以顺利编译；但不知道CJKnumb的功能是否保留？
3. 将CJKnumb更换为zhnumber，xelatex可以正常编译；但不知道功能是否正常？

**Comment by polossk** [comment]
您好，我的本地环境是 texlive2018，目前 @cfrpg 正在安装最新环境，请等待他测试之后给您反馈

**Comment by LuckySquirrel** [comment]
> 经过测试，2021版确实有bug，但目前模板中实际没有用到中文编号，因此去除CJKnumb或者更换为zhnumber都可以正常编译。

好的，感谢dalao
