### ISSUE TITLE
[BUG]大量Missing number, treated as zero.错误

### ISSUE THREAD

**Issue by SnailForce** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#40]
出现大量Missing number, treated as zero.错误
没有修改任何地方

**Comment by polossk** [comment]
您好！

如果方便，请留下一份最小运行环境，或者说明下您的工作环境，或者一些截图以方便我们判断是否为模板自身的问题。

**Comment by SnailForce** [comment]
确实所有中文的地方都报这个错误，您知道该如何解决吗，我是直接通过github desktop下载下来，然后本地texstudio编译的

**Comment by FlirtD** [comment]
> 在win10上报错，背页上超时

将thesis-setting.tes文件中的\usepackage{CJKnumb}注释或删除即可

**Comment by FlirtD** [comment]
> 出现大量缺失数，视为零。错误 没有修改任何地方

将thesis-setting.tes文件中的\usepackage{CJKnumb}注释或删除即可

**Comment by FlirtD** [comment]
将thesis-setting.tes文件中的\usepackage{CJKnumb}注释或删除即可

**Comment by taohan10200** [comment]
> 将thesis-setting.tes文件中的\usepackage{CJKnumb}注释或删除即可
注释了确实可以，这是什么原理呢？

**Comment by polossk** [comment]
>> 将thesis-setting.tes文件中的\usepackage{CJKnumb}注释或删除即可
>
>注释了确实可以，这是什么原理呢？

我猜测可能是 CJKnumb 这个库不知道哪里冲突了吧，我们后续会处理这个问题，感谢大家集思广益
