### ISSUE TITLE
[Suggestion]上下页边距不满足要求

### ISSUE THREAD

**Issue by xuezhangzx** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#41]
模板中设置的上下边距为2.54cm，但是打印出来上边距偏大3cm下边距小2cm。
请问有没有遇到这种问题？

windows环境，texstudio，xelatex编译

**Comment by polossk** [comment]
您好！

我们没有接到类似的问题的汇报。您可以参考如下流程进行检查与修复：

1. 请优先查看 PDF 的输出结果的页边距是否满足要求，排除 PDF 自身的问题：如果 PDF 本身的上下页边距有问题，请定位文件 [`setting/thesis-setting.tex`](https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/blob/master/settings/thesis-setting.tex) 的第 22 行关于 A4 纸张的页边距定义，请按照实际输出的 PDF 页边距，手动微调 `top` 和 `bottom` 的数值。
2. 如果 PDF 的输出结果的页边距满足 2.54 cm 的大小，您可能需要检查打印机的相关设置。或者您也可以按上述修改方案，手动微调相关数值，将打印机的输出结果与之匹配。
