### ISSUE TITLE
[Suggestion] 公式字体不是times new roman

### ISSUE THREAD

**Issue by dafeifeifeifeige** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#43]
请问如何将公式字体修改为Times new roman

![Equation](https://user-images.githubusercontent.com/66540330/152665856-31258278-2124-4a44-a8b1-2d16569b8196.jpg)

**Comment by dafeifeifeifeige** [comment]
正文的英文也不是Times new roman
![image](https://user-images.githubusercontent.com/66540330/152666334-4d5231c2-5808-4161-ba6e-6e30508914cd.png)

**Comment by polossk** [comment]
您好！

我刚刚查阅了西工大的论文规范，里面没有明确指定具体的公式字体，但是材料中提到了西文字体和一个公式的样例，如图所示。

> 西文字体规范
> <img width="1625" alt="截屏2022-02-12 10 58 39" src="https://user-images.githubusercontent.com/7643570/153694106-07c20bf4-db41-403b-a650-cbcf1c725efb.png">
> 公式样例
> <img width="1625" alt="截屏2022-02-12 10 54 14" src="https://user-images.githubusercontent.com/7643570/153693974-e1403453-a5ff-449c-b538-fde34c2490ff.png">

从样例来看，这里的确使用的是 Times New Roman。

不过一般来说，就我目前所看到的硕博大论文或者期刊论文的情况来讲，一般都是选择默认字体或者期刊指定的模板字体。而且公式中有些符号，比如花体、加粗、正体等，确实使用了不同的字体。我的个人建议是，您可以暂时不管这个问题，如果送审前有老师问到，再做统一更改。

如果需要更改，可以参考这个步骤<https://stone-zeng.github.io/2020-05-02-use-opentype-fonts-iii/>：

1. 从 <https://github.com/aliftype/xits> 上直接下载整个repo
2. 安装所有的 `otf` 字体文件
3. 在 [`setting/thesis-setting.tex`](https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/blob/master/settings/thesis-setting.tex) 的文件末尾，添加
```tex
\setmainfont{XITS}       % XITS 是 Times Roman 的开源复刻版本
\setmathfont{XITS Math}  % XITS Math 是与之匹配的数学字体
```

您试一下，期待您的回复。
