### ISSUE TITLE
[BUG]按照readme说明，编译硕士论文失败

### ISSUE THREAD

**Issue by obliviate1230** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#50]
**描述您的问题 (Describe the bug)**
按照readme说明，将degree=phd改为degree=mst后，编译的pdf仍然为博士论文的版本

**环境与版本信息**
1. 代码版本(Code version)（留空则默认最新）：
2. 操作系统 (OS)：macOS
3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：MacTex
4. Tex 编译器 (Tex compiler, eg. XeTeX):  XeLaTex

** 附加内容 (Other info, bugs and logs)**

在yanputhesis.cls中的31-33行中定义如下
\def\set@type@phd{     \@npu@type@phdtrue\@npu@type@mstfalse\@npu@type@bclfalse}
\def\set@type@master{  \@npu@type@phdfalse\@npu@type@msttrue\@npu@type@bclfalse}
\def\set@type@bachelor{\@npu@type@phdfalse\@npu@type@mstfalse\@npu@type@bcltrue}

所以在tex文件中应该使用degree=master来生成硕士学位论文

**Comment by polossk** [comment]
您好！感谢指出问题，我们会在 readme 中加以修改！

**Comment by polossk** [comment]
已更新
