### ISSUE TITLE
[BUG] 页眉编号有误？大概

### ISSUE THREAD

**Issue by sagestar** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#51]
页眉部分编译后会出现章节编号重复。

比方说绪论，编译之后页眉显示“1 1. 绪论”，尝试编辑cls页眉块，失败了T_T

总之就是，前面的章节编号显示两遍，“2 2. 相关知识”。类似这种。

章节数字+空格+章节数字+.+章节标题。

此外不知道是不是我的问题，win10环境，adobe song std字体无法编译，所以在document里面改为adobe=false。因为下载下来的adobe song std字体都是叫做adobe song std light。编译会出现一些符号already defined或者缺少adobe song std。
如果可以的话，希望提供一些指导。

感谢你们的工作，latex比word好用多了！

**Comment by polossk** [comment]
页眉问题：本人使用过程中未发现这种情况，请提供一个最小复现样例。

字体这个：Windows下测试过，没有问题，他字体的名字就叫 adobe song std light，你下载的字体文件应该是对着的。

所以可能是自己的环境出错了？

**Comment by sagestar** [comment]
**就是最新的版本，解压直接编译，win10, 联想小新pro13，texliv2020，控制台报错：**

> This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex)
>  restricted \write18 enabled.
> entering extended mode
> (./yanputhesis-sample.tex
> LaTeX2e <2020-02-02> patch level 5
> L3 programming layer <2020-03-06> (./yanputhesis.cls
> Document Class: yanputhesis 2022/02/18 v1.6.0 Yet Another NPU Thesis Template
> (d:/texlive/2020/texmf-dist/tex/latex/xkeyval/xkeyval.sty
> (d:/texlive/2020/texmf-dist/tex/generic/xkeyval/xkeyval.tex
> (d:/texlive/2020/texmf-dist/tex/generic/xkeyval/xkvutils.tex
> (d:/texlive/2020/texmf-dist/tex/generic/xkeyval/keyval.tex))))
> (d:/texlive/2020/texmf-dist/tex/latex/base/book.cls
> Document Class: book 2019/12/20 v1.4l Standard LaTeX document class
> (d:/texlive/2020/texmf-dist/tex/latex/base/bk11.clo))
> (d:/texlive/2020/texmf-dist/tex/latex/geometry/geometry.sty
> (d:/texlive/2020/texmf-dist/tex/generic/iftex/ifvtex.sty
> (d:/texlive/2020/texmf-dist/tex/generic/iftex/iftex.sty)))
> (d:/texlive/2020/texmf-dist/tex/latex/hyperref/hyperref.sty
> (d:/texlive/2020/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
> (d:/texlive/2020/texmf-dist/tex/latex/pdftexcmds/pdftexcmds.sty
> (d:/texlive/2020/texmf-dist/tex/generic/infwarerr/infwarerr.sty))
> (d:/texlive/2020/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)
> (d:/texlive/2020/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)
> (d:/texlive/2020/texmf-dist/tex/generic/pdfescape/pdfescape.sty)
> (d:/texlive/2020/texmf-dist/tex/latex/hycolor/hycolor.sty)
> (d:/texlive/2020/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)
> (d:/texlive/2020/texmf-dist/tex/latex/auxhook/auxhook.sty)
> (d:/texlive/2020/texmf-dist/tex/latex/kvoptions/kvoptions.sty)
> (d:/texlive/2020/texmf-dist/tex/latex/hyperref/pd1enc.def)
> (d:/texlive/2020/texmf-dist/tex/generic/intcalc/intcalc.sty)
> (d:/texlive/2020/texmf-dist/tex/generic/etexcmds/etexcmds.sty)
> (d:/texlive/2020/texmf-dist/tex/latex/hyperref/puenc.def)
> (d:/texlive/2020/texmf-dist/tex/latex/url/url.sty)
> (d:/texlive/2020/texmf-dist/tex/generic/bitset/bitset.sty
> (d:/texlive/2020/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))
> (d:/texlive/2020/texmf-dist/tex/generic/atbegshi/atbegshi.sty))
> (d:/texlive/2020/texmf-dist/tex/latex/hyperref/hxetex.def
> (d:/texlive/2020/texmf-dist/tex/generic/stringenc/stringenc.sty)
> (d:/texlive/2020/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty
> (d:/texlive/2020/texmf-dist/tex/latex/atveryend/atveryend.sty)
> (d:/texlive/2020/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty)))
> 
> Package hyperref Warning: Option `bookmarks' has already been used,
> (hyperref)                setting the option has no effect on input line 64.
> 
> (d:/texlive/2020/texmf-dist/tex/latex/type1cm/type1cm.sty)
> (d:/texlive/2020/texmf-dist/tex/latex/ifplatform/ifplatform.sty
> (d:/texlive/2020/texmf-dist/tex/latex/tools/shellesc.sty)
> (d:/texlive/2020/texmf-dist/tex/generic/catchfile/catchfile.sty)
> (d:/texlive/2020/texmf-dist/tex/generic/iftex/ifluatex.sty)
> 
> Package ifplatform Warning: 
>     shell escape is disabled, so I can only detect \ifwindows.
> 
> ) (d:/texlive/2020/texmf-dist/tex/latex/fontspec/fontspec.sty
> (d:/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
> (d:/texlive/2020/texmf-dist/tex/latex/l3kernel/expl3.sty
> (d:/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-xdvipdfmx.def)))
> (d:/texlive/2020/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
> (d:/texlive/2020/texmf-dist/tex/latex/base/fontenc.sty)
> (d:/texlive/2020/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
> (d:/texlive/2020/texmf-dist/tex/xelatex/xecjk/xeCJK.sty
> (d:/texlive/2020/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
> (d:/texlive/2020/texmf-dist/tex/latex/l3packages/xtemplate/xtemplate.sty)
> (d:/texlive/2020/texmf-dist/tex/xelatex/xecjk/xeCJK.cfg))
> 
> ! Package fontspec Error: The font "Adobe Song Std" cannot be found.
> 
> For immediate help type H <return>.
>  ...                                              
>                                                   
> l.114 ...ltKai, BoldFont=\defaultHei]{\defaultSog}
>                                                   
> ? 

**Error和Warning：**

> yanputhesis.cls
> 114
> Package fontspec Error: The font "Adobe Song Std" cannot be found.
> 
> For immediate help type H <return>.
>  ...                                              
>                                                   
> l.114 ...ltKai, BoldFont=\defaultHei]{\defaultSog}
> yanputhesis.cls
> 64
> Package hyperref Warning: Option `bookmarks' has already been used, setting the option has no effect on input line 64.

**关于字体，因为我虽然单独装了字体，不过也装了PS和AI，字体本身应该也没问题。**
我在实际使用中，是使用了false的：

> \documentclass[lang=chs, degree=phd, blindreview=false, adobe=false]{yanputhesis}

然后就编译通过了。
编译过了以后就出现这个双章节序号的问题，包括附录，有俩“附录”。
[yanputhesis-sample.pdf](https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/files/9075926/yanputhesis-sample.pdf)

我所进行的唯一的改动就是改了个false。上面的编译过程应该是显示了我的所有信息。
回复辛苦了。
这是我下载的版本，一并上传。
[Yet-Another-LaTeX-Template-for-NPU-Thesis-master.zip](https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/files/9075929/Yet-Another-LaTeX-Template-for-NPU-Thesis-master.zip)

希望只是我自己的问题，当然没问题最好，多谢。

**Comment by sagestar** [comment]
我尝试了一下，字体的问题在于，在windows下安装字体时需要右键“为所有用户安装”。
但是页眉双编号的问题还是有。

**Comment by sagestar** [comment]
换了实验室的电脑，还是windows下编译还是双章节编号。不知道问题在哪里。

**Comment by polossk** [comment]
额，我这边跑了下你的zip，结果是正常的orz
[yanputhesis-sample.pdf](https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/files/9079201/yanputhesis-sample.pdf)

**Comment by polossk** [comment]
我的本地环境是
```shell
xelatex --version
XeTeX 3.141592653-2.6-0.999993 (TeX Live 2021)
kpathsea version 6.3.3
Copyright 2021 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 68.2; using 68.2
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.10.4; using 2.10.4
Compiled with Graphite2 version 1.3.14; using 1.3.14
Compiled with HarfBuzz version 2.7.4; using 2.7.4
Compiled with libpng version 1.6.37; using 1.6.37
Compiled with pplib version v2.05 less toxic i hope
Using Mac OS X Core Text and Cocoa frameworks
```
我一会找下我的旧 Windows 电脑跑一下

**Comment by polossk** [comment]
已确认，是 Windows 下的问题，我排查下，您先继续写大论文

**Comment by polossk** [comment]
已定位是 `fancyhdr` 包中的 leftmark 的问题

**Comment by polossk** [comment]
问题解决，请更新 fancyhdr 包，实测更新后就没事了
[归档.zip](https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/files/9079281/default.zip)

在你的电脑上的路径大概是：
`D:\texlive\2020\texmf-dist\tex\latex\fancyhdr`

**Comment by sagestar** [comment]
搞定了，确实是更新后就好了，辛苦了。

**Comment by zqxyus** [comment]
> 问题解决，请更新 fancyhdr 包，实测更新后就没事了 [归档.zip](https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/files/9079281/default.zip)
> 
> 在你的电脑上的路径大概是： `D:\texlive\2020\texmf-dist\tex\latex\fancyhdr`

我的texlive 版本 2020, 替换更新fancyhdr包后，页眉两个编号问题解决了，
但是有一个新的问题就是 页眉 出现   “第  章绪论”，  即章的序号缺失！ 怎么解决呢？ 先谢！
