### ISSUE TITLE
[Suggestion]建议收容所有需要的字体，linux下一般无预装字体

### ISSUE THREAD

**Issue by debeetle** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#52]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
1. 代码版本(Code version)（留空则默认最新）：
2. 操作系统 (OS)：
3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：
4. Tex 编译器 (Tex compiler, eg. XeTeX): 

**你的建议是否和一个已知问题有关 (Is your feature request related to a problem? Please describe.)**
简洁、精准的概括您的问题(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])

**告诉我们你想要的解决方案(Describe the solution you'd like)**
简介而精准的告诉我们你想要怎么样 (A clear and concise description of what you want to happen.)

**告诉我们你想到的其他替代方案(Describe alternatives you've considered)**
简介而精准的告诉我们其他替代方案 (A clear and concise description of any alternative solutions or features you've considered.)

**其他信息(Additional context)**
添加有关这个建议的其他信息，例如截图(Add any other context or screenshots about the feature request here.)

**Comment by polossk** [comment]
额，版权问题，恕难从命orz
