### ISSUE TITLE
怎么把章节 1 改为 “第一章”

### ISSUE THREAD

**Issue by dafeifeifeifeige** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#55]
尽管和学校模板不一样，但老师要求将1 改为 “第一章”

**Comment by polossk** [comment]
尽管你的要求很合理，但是：
> 模板成型于 2022 年。如果后期有任何格式上的变化，欢迎 fork-modify-pull-request 或者在 issue 中详细说明新旧格式之差异，我们乐意解决模板使用的问题
> **恕制作者们不解答任何 LaTeX 使用问题**
请自行百度
