### ISSUE TITLE
编译报错[BUG]

### ISSUE THREAD

**Issue by xiaozhamao** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#56]

**Comment by xiaozhamao** [comment]
您好，我在编译的过程中遇到了一些问题。
在overleaf，texstudio，TeXworks editor上都没办法正常使用，想确认下编译器是pdflatex，xelatex还是lualatex。
我目前采用的是pdflatex，报错为
(fontspec)                      LuaTeX.
(fontspec)                      
(fontspec)                      You must change your typesetting engine to,
(fontspec)                      e.g., "xelatex" or "lualatex" instead of
(fontspec)                      "latex" or "pdflatex".

Type <return> to continue.
 ...                                              
                                                  
l.45 \msg_fatal:nn {fontspec} {cannot-use-pdftex}

当我按照要求改为xelatex或者lualatex会出现更多的错误。在尝试编译别的tex文件时没有问题的。
想问下应该如何设置，期待您的解答。

**Comment by polossk** [comment]
请贴出您的错误。我们一直都是使用xelatex编译的，没有出现错误

**Comment by polossk** [comment]
尚未得到提问者回复，关闭该issue
