### ISSUE TITLE
[Suggestion]学校发了新模板，请问您会继续更新吗？

### ISSUE THREAD

**Issue by sooyio** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#57]
学校发了新模板，请问您会继续更新吗？

**Comment by cfrpg** [comment]
你好，能否提供一下最新模板文件？

**Comment by sooyio** [comment]
http://gs.nwpu.edu.cn/info/2284/15346.htm

**Comment by polossk** [comment]
您好！我们正在处理中，新模板影响23年1月1日之后答辩的博士、硕士，之前的先用旧模板。

**Comment by qwe93450** [comment]
您好， 请问新模板改动大吗，我是23年1月1日之后答辩的硕士

**Comment by polossk** [comment]
改动不大，您先完成论文主体内容，耐心等待模板更新。

**Comment by LiaoYujia** [comment]
同是23年1月之后答辩的硕士，十分感谢作者的latex模板，2020年本科毕业就是用的您的模板，硕士毕业还继续用您的模板

**Comment by qwe93450** [comment]
> 改动不大，您先完成论文主体内容，耐心等待模板更新。

好的，谢谢作者，支持支持！

**Comment by polossk** [comment]
已更新 @sooyio @LiaoYujia @qwe93450

**Comment by LiaoYujia** [comment]
> 已更新 @sooyio @LiaoYujia @qwe93450

十分感谢！
