### ISSUE TITLE
初始项目编译出的参考文献不显示，同时引用文献的位置为“?”

### ISSUE THREAD

**Issue by Fduiosss** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#65]
![image](https://user-images.githubusercontent.com/38063257/205959314-45326ac4-bc5f-4a3f-aec7-74fbf9700f17.png)

如上图所示，初始项目没有使用修改任何东西，vscode,和tex live2020正常编译，其他一切展示正常，请问下这个是什么原因啊，网上搜了一些解决办法，并不适用。

**Comment by polossk** [comment]
xelatex + bibtex + xelatex + xelatex 编译下试试

**Comment by polossk** [comment]
请清理所有的临时文件，并按照 xelatex + bibtex + xelatex + xelatex 顺序编译，或者您可提供报错信息

**Comment by Fduiosss** [comment]
感谢，我在重新试试

**Comment by polossk** [comment]
如果没有问题将关闭 issue

**Comment by Fduiosss** [comment]
试了，没用。。。主要是编译不报错，我也不知道问题出在哪里

**Comment by polossk** [comment]
如果方便，请按照如下操作依次执行：
1. 清空目前所有的临时文件，只保留 `*.bst`，`*.tex`，`*.cls` 等核心文件；
2. 单独执行 `xelatex artical-local.tex` 命令；
3. 单独执行 `bibtex artical-local.aux` 命令；

请将执行 `bibtex artical-local.aux` 命令后的输出复制粘贴出来，如果方便请上传 log 文件，方便定位错误。

**Comment by Fduiosss** [comment]
行，我再试试，不行了我换个软件试试

**Comment by Fduiosss** [comment]
texlive2020编译始终解决不了这个问题，换了个软件texmaker，执行 xelatex + bibtex + xelatex + xelatex 编译文献正常显示，已经解决问题，感谢~

**Comment by polossk** [comment]
感谢反馈！
