### ISSUE TITLE
[BUG]硕士论文格式不对

### ISSUE THREAD

**Issue by ZPyan-npu** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#69]
硕士论文格式调不出来，初步认为是因为cls文件里面mst勿敲为了全称master

32-34行应为：
\def\set@type@mst{\@npu@type@phdfalse\@npu@type@msttrue\@npu@type@bclfalse}
\def\set@type@bcl{\@npu@type@phdfalse\@npu@type@mstfalse\@npu@type@bcltrue}

感谢作者的模板！

**Comment by polossk** [comment]
感谢反馈，我们将于近期处理下

**Comment by dijkstra123** [comment]
你好，ctex似乎无法运行

**Comment by LiaoYujia** [comment]
> 硕士论文格式调不出来，初步认为是因为cls文件里面mst勿敲为了全称master
> 
> 32-34行应为： \def\set@type@mst{@NPU@type@phdfalse@npu@type@msttrue@npu@type@bclfalse} \def\set@type@bcl{@NPU@type@phdfalse@npu@type@mstfalse@npu@type@bcltrue}
> 
> 感谢作者的模板！

同学，你这里指的是硕士论文中的哪些格式调不出来呢？
我  cls文件里 
32-34行 是 
\def\set@type@master{  \@npu@type@phdfalse\@npu@type@msttrue\@npu@type@bclfalse}
\def\set@type@bachelor{\@npu@type@phdfalse\@npu@type@mstfalse\@npu@type@bcltrue}

**Comment by LiaoYujia** [comment]
> 硕士论文格式调不出来，初步认为是因为cls文件里面mst勿敲为了全称master
> 
> 32-34行应为： \def\set@type@mst{@NPU@type@phdfalse@npu@type@msttrue@npu@type@bclfalse} \def\set@type@bcl{@NPU@type@phdfalse@npu@type@mstfalse@npu@type@bcltrue}
> 
> 感谢作者的模板！

有没有试过 作者提到过的 
https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/issues/50
这个解决方案呢？

**Comment by ZPyan-npu** [comment]
我就是把所有的master改为了mst，bachelor改为了bcl，统一了一下，这样就ok了

**Comment by polossk** [comment]
抱歉，之前的版本主要用于几位博士的大论文格式，硕士的疏于管理和维护，近期会根据反馈更新一下。

**Comment by polossk** [comment]
#74 #75 已解决 README 描述不当的问题
