### ISSUE TITLE
[BUG]如何修改学位

### ISSUE THREAD

**Issue by CarlDegio** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#70]
**描述您的问题 (Describe the bug)**

在tex中修改degree=bcl或mst，生成的pdf仍然是博士学位论文。

**环境与版本信息**
1. 代码版本(Code version)（留空则默认最新）：
2. 操作系统 (OS)：windows
3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：2022
4. Tex 编译器 (Tex compiler, eg. XeTeX): xelatex

**可复现内容 (Reproduceable steps)**

修改了.tex初始语句，`\documentclass[lang=chs, degree=bcl, blindreview=false, adobe=true]{yanputhesis}`，生成的pdf仍然是博士学位论文。

** 附加内容 (Other info, bugs and logs)**

可能还需要同步修改yanputhesis.cls的格式内容？

**Comment by CarlDegio** [comment]
设置bachelor或者master就可以了，发现是一个已经提过的问题

**Comment by polossk** [comment]
参考 #50
