### ISSUE TITLE
[BUG]CTEX无法运行

### ISSUE THREAD

**Issue by dijkstra123** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#71]
win11 使用ctex2.9无法成功编译

报错信息、日志、可复现的代码片段 (Describe your current behavior and code to reproduce the issue)*（Xelatex）
! Undefined control sequence.
l.263 \theorempreskip
                     {0pt}

**Comment by polossk** [comment]
不支持 CTEX
CTEX 2.9 过于陈旧，请使用 texlive 2021 之后的版本
