### ISSUE TITLE
同一个页眉两个编号问题[BUG]

### ISSUE THREAD

**Issue by SongPapers** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#72]
**页眉出现两个编号**

*原版运行后文章的页眉出现两个编号问题：如第一章绪论的页眉为  第 1 章 1. 绪论*

**Comment by SongPapers** [comment]
使用编译器为TexLive2020，windows环境

**Comment by SongPapers** [comment]
编译器切换为TexLive2022，上述问题消失，bug原因可能与编译器版本相关，但无法具体定位。

**Comment by polossk** [comment]
参考 #51
