### ISSUE TITLE
[Suggestion]2023年的新模板加了一个 评阅人和答辩委员会名单

### ISSUE THREAD

**Issue by JackLiujie** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#73]
我看2023年的新模板里有一个 评阅人和答辩委员会名单，在摘要页前面，咱最近更新的模板好像没有这一页。还是说这一页只是单独的附件，不用加在整个论文里，谢谢。辛苦了。

**Comment by polossk** [comment]
新模板尚未制作这一页，因为我们也不知道这一页用不用放进论文当中。
如果有需要，推荐使用学校给的word模板直接填写答辩委员与评阅人名单即可。
猜测论文送审时并不需要这一页。很可能是最后提交学校时才用到，后续可能会更新一个单独页方便大家填写。
