### ISSUE TITLE
[Suggestion] 关于英文部分的逗号问题及名单问题

### ISSUE THREAD

**Issue by WhistleO** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#79]
1. Xi’an P. R. China 按照手册，应该没有逗号
2. 学位论文一般由十一个部分组成，依次为：1.封面；2.中文、英文题名页；**3.评阅人和答辩委员会名单**；4.中文、英文摘要；5.目录页；6.正文；7.参考文献；8.附录；9.致谢；10.在学期间发表的学术成果和参加科研情况；11.声明。 第三部分没有

**Comment by LiaoYujia** [comment]
第一个问题，编辑yanputhesis.cls中643行        \fEng \sXiaosan Xi'an P.R. China \\                %
删去逗号就行了。
第二个问题，自己现在是打算写word然后转pdf插入到最后的论文中。

**Comment by polossk** [comment]
感谢反馈
问题 1：应该是我们的 bug，会尽快修正；
问题2：答辩委员会名单目前着急的话请直接使用word编写，然后打印成pdf并插入至最终上传论文当中。后续等格式调整合适后会发布相关更新。

**Comment by polossk** [comment]
@WhistleO 针对问题 1：我查询了相关语法说明，城市与州、国家之间应当添加逗号表示间隔。所以如果有评审问到这个问题，我的建议是听评审专家的，否则我个人倾向使用正确语法而非学校参考标准。
针对问题 2：预计近日更新使用方法
