### ISSUE TITLE
[BUG]标题数字部分也应该黑体吧

### ISSUE THREAD

**Issue by WhistleO** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#80]
示例给的是黑体，包括英文部分（数字）。
3.5.1 标题
一级标题：黑体，三号，段前0.5行，段后0行，固定行间距20pt。编辑时，在一级标题前、后各留一空行（宋体，小四号，单倍行距）。
二级标题：黑体，四号，段前0.5行，段后0行，固定行间距20pt。
三级标题：黑体，小四号，段前0.5行，段后0行，固定行间距20pt。

**Comment by LiaoYujia** [comment]
+1，遇到同样的问题，不太清楚如何编辑yanputhesis.cls文件使得标题部分的数字的字体为黑体。

**Comment by polossk** [comment]
感谢反馈，会尽快测试并给出修正

**Comment by polossk** [comment]
> > 感谢反馈，会尽快测试并给出修正
> 
> 想额外咨询作者关于修改子图序号字体的问题，写作指南中给的示例，子图的序号括号为宋体，字母a为新罗马，与您提供的子图使用方法中的字体不同。自己latex学得不多，也改了好久没改出来，目前是在yanputhesis.cls的 \captionsetup[subfigure]{labelformat=simple, aboveskip=0pt} %增加两条语句：
> 
> \DeclareCaptionFont{test}{\CJKfamily{song}} % \captionsetup[subfigure]{labelfont=test,labelformat=simple, aboveskip=0pt} %
> 
> 但是失效了，想咨询作者有没有好的修改方式呢？十分感谢您。

您的观察确实很细致，这个问题我们都没有注意到，统一使用英文小括号来标记了。

当然您这个问题也可以解决，参考 `caption` 包的文档（通过命令 `texdoc caption` 访问），内部给出了 `\DeclareCaptionLabelFormat{name}{code using #1 and #2i}` 命令来设置自定义编号格式。
如：
```tex
\DeclareCaptionLabelFormat{bf-parens}{(\textbf{#2})}
\captionsetup{labelformat=bf-parens,labelsep=quad}
```
会输出加粗版本的子标题编号（如图1(**2**)）
所以我猜测应该写成

```tex
\DeclareCaptionLabelFormat{chs-parens}{（#2）}
\captionsetup[subtable]{labelformat=chs-parens, aboveskip=0pt}  %
\captionsetup[subfigure]{labelformat=chs-parens, aboveskip=0pt} %
```
就可以解决你的问题

**Comment by LiaoYujia** [comment]
> > > 感谢反馈，会尽快测试并给出修正
> > 
> > 
> > 想额外咨询作者关于修改子图序号字体的问题，写作指南中给的示例，子图的序号括号为宋体，字母a为新罗马，与您提供的子图使用方法中的字体不同。自己latex学得不多，也改了好久没改出来，目前是在yanputhesis.cls的 \captionsetup[subfigure]{labelformat=simple, aboveskip=0pt} %增加两条语句：
> > \DeclareCaptionFont{test}{\CJKfamily{song}} % \captionsetup[subfigure]{labelfont=test,labelformat=simple, aboveskip=0pt} %
> > 但是失效了，想咨询作者有没有好的修改方式呢？十分感谢您。
> 
> 您的观察确实很细致，这个问题我们都没有注意到，统一使用英文小括号来标记了。
> 
> 当然您这个问题也可以解决，参考 `caption` 包的文档（通过命令 `texdoc caption` 访问），内部给出了 `\DeclareCaptionLabelFormat{name}{code using #1 and #2i}` 命令来设置自定义编号格式。 如：
> 
> ```
> \DeclareCaptionLabelFormat{bf-parens}{(\textbf{#2})}
> \captionsetup{labelformat=bf-parens,labelsep=quad}
> ```
> 
> 会输出加粗版本的子标题编号（如图1(**2**)） 所以我猜测应该写成
> 
> ```
> \DeclareCaptionLabelFormat{chs-parens}{（#2）}
> \captionsetup[subtable]{labelformat=chs-parens, aboveskip=0pt}  %
> \captionsetup[subfigure]{labelformat=chs-parens, aboveskip=0pt} %
> ```
> 
> 就可以解决你的问题

感谢您的回复，我尝试了下，还是有不对。
目前变成了（（a）），多了括号。

**Comment by polossk** [comment]
RE: @LiaoYujia 我阅读了关于括号的部分，其中公式编号的括号明确注明了使用英文小括号，子图只能找到样例，我猜测可能得翻阅各个学会自己的格式要求（如果有的话），例如我还见过图表标题同时需要中英双语的。所以我个人建议应该没有硬性规定，只要保持全文风格统一即可。

如果您认同我上面的这个想法的话，我就不往模板中更新咯（手动偷懒狗头
