### ISSUE TITLE
[Suggestion]关于section和subsection以及subsubsection的编号没有左对齐的问题

### ISSUE THREAD

**Issue by siegfriedre** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#86]
关于section和subsection以及subsubsection的编号没有左对齐的问题。
正常编译之后发现小标题（如：1.2 国内外研究现状，1.2.1 xxxx）没有左对齐。
经过测试，发现cls文件第169行的命令\titleformat{\section}[hang]{\sffamily\fHei\sSihao}{\sffamily\fHei\sSihao\thesection}{0.5em}{}{}被写成了两行，即多了一个回车（subsection和subsubsection同理）。将回车删除之后编译，即可左对齐。

**Comment by polossk** [comment]
已确认是 bug，修复后请下载最新版本

**Comment by polossk** [comment]
已确认是 bug，请等待更新
