### ISSUE TITLE
[Suggestion] 目录页不能有目录索引

### ISSUE THREAD

**Issue by WhistleO** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#88]
![错误.png](https://s2.loli.net/2023/03/07/rcmvfQaRKn84G9h.png)

![正确.png](https://s2.loli.net/2023/03/07/rYRLFlj2WA4Hv3T.png)

**Comment by polossk** [comment]
`yanputhesis.cls` 752 行注释掉

**Comment by polossk** [comment]
目前已更新，请下载最新版本 https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/archive/refs/heads/polossk-dev.zip

**Comment by polossk** [comment]
如果方便的话，可否留下姓名或学院，会在README中署名鸣谢
