### ISSUE TITLE
[Suggestion] 关于英文封面

### ISSUE THREAD

**Issue by WhistleO** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#91]
最新要求里面，对于英文封面部分，没有专业加粗的要求了。
\fEng {\nwpu@eng@degree} of \textbf{\nwpu@eng@major}

改为
\fEng {\nwpu@eng@degree} of {\nwpu@eng@major}

**Comment by LiaoYujia** [comment]
这个很有争论，咱们学校的指南写的太不用心了。博士英文封面的专业是加粗的，硕士不加粗。

**Comment by polossk** [comment]
自行修改
