### ISSUE TITLE
[Suggestion]关于中文标题页和英文标题页排版太靠上的问题

### ISSUE THREAD

**Issue by LiaoYujia** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#92]
今天打印出来发现 
（1）中文标题页中的“西北工业大学”离上面页边太近了。
（2）英文标题页中的题目 离上面页边太近了。
问题如图（同等比例）：
![1678262678186](https://user-images.githubusercontent.com/45456623/223656024-64a0e390-880c-405d-86a3-3c991a5578e0.png)
对比同学用word模板的：
![1678262725033](https://user-images.githubusercontent.com/45456623/223656174-bf10ce77-862c-4ce3-9903-ea49106838b7.png)

尝试修改yanputhesis.cls中的设置中文标题页，
        \fSong \sSanhao \par \vspace{1\baselineskip}        % 1 * 21pt * 1.5
 修改为
         \fSong \sSanhao \par \vspace{3\baselineskip}        % 1 * 21pt * 1.5 
 没有work。
 
想咨询作者如何修改，快到交论文的ddl了。十分感谢！

**Comment by polossk** [comment]
太靠上的原因是因为，打印裁剪的时候需要留出余量，可能不同的打印方式会导致余量不同。

对于你这种情况，直接修改为
```tex
\fSong \sSanhao \par \vspace*{2\baselineskip} % 1 * 21pt * 1.5
```
加星号强制输出空行，后续自行调节吧。

**Comment by LiaoYujia** [comment]
了解了，感谢作者！

**Comment by polossk** [comment]
后续将在README中说明，不再合并至主要分支当中
