### ISSUE TITLE
[BUG]子图的标题行间距

### ISSUE THREAD

**Issue by obliviate1230** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#93]
**描述您的问题 (Describe the bug)**

编译后的文本，子图的标题会紧贴在图片的下方，比如样例中给的图2-2的子图标题就紧贴在图片下方，按照论文规范，子图的的标题固定行间距为20pt。

**环境与版本信息**
1. 代码版本(Code version)（留空则默认最新）：
2. 操作系统 (OS)：Windows 10 
3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：Texlive 2022
4. Tex 编译器 (Tex compiler, eg. XeTeX):  XeTex

** 附加内容 (Other info, bugs and logs)**

应该对cls文件中的第260行进行相应修改，原先的aboveskip=0pt应该被修改。

**Comment by LeiSir16** [comment]
请问，这个问题您已经解决了么，是怎么解决的？我目前也遇到了这个问题，修改了aboveskip之后图片大标题后面就会空白好多

**Comment by CongzhuoFang** [comment]
由于tex中图片和表格都属于浮动体, 所以图片标题的行间距可能不会完全符合设置. 如果想调节子标题和子图的间距, 可以通过在`\includegraphics{}`命令下方添加间距控制命令`\vspace*{}`, 刚刚试了一下20pt个人感觉略大, 具体大小可以调调试一下. 

```latex
\begin{figure}[htb]
    \centering
    \begin{minipage}[t]{0.96\textwidth}
        \centering
        \begin{subfigure}[t]{0.47\textwidth}
            \centering
            \includegraphics[scale=0.1]{poster.png}
            \vspace*{1em}
            \caption{\label{subfig:example2-subfig1}}
        \end{subfigure}
        \begin{subfigure}[t]{0.47\textwidth}
            \centering
            \includegraphics[scale=0.1]{poster.png}
            \vspace{10pt}
            \caption{\label{subfig:example2-subfig2}}
        \end{subfigure}
    \end{minipage}
    \caption{这里是另一个普通的标题}
    \label{fig:example2}
\end{figure}
```

**Comment by note286** [comment]
统一设置比较好。

```latex
\documentclass{ctexbook}
\usepackage{graphicx}
\usepackage{subcaption}
\subcaptionsetup[figure]{skip=20pt}
\begin{document}
\begin{figure}
\centering
\subcaptionbox{aaa\label{aaa}}{\includegraphics[width=.3\linewidth]{example-image}}\hfill
\subcaptionbox{aaa\label{aaa}}{\includegraphics[width=.3\linewidth]{example-image}}\hfill
\subcaptionbox{aaa\label{aaa}}{\includegraphics[width=.3\linewidth]{example-image}}
\caption{bbb}
\label{bbb}
\end{figure}
\end{document}
```

![image](https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/assets/16207292/403edcfb-ce72-4801-a654-9fd23759c4e2)

**Comment by polossk** [comment]
> 统一设置比较好。
> 
> ```
> \documentclass{ctexbook}
> \usepackage{graphicx}
> \usepackage{subcaption}
> \subcaptionsetup[figure]{skip=20pt}
> \begin{document}
> \begin{figure}
> \centering
> \subcaptionbox{aaa\label{aaa}}{\includegraphics[width=.3\linewidth]{example-image}}\hfill
> \subcaptionbox{aaa\label{aaa}}{\includegraphics[width=.3\linewidth]{example-image}}\hfill
> \subcaptionbox{aaa\label{aaa}}{\includegraphics[width=.3\linewidth]{example-image}}
> \caption{bbb}
> \label{bbb}
> \end{figure}
> \end{document}
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/16207292/286459041-403edcfb-ce72-4801-a654-9fd23759c4e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjY2NDAsIm5iZiI6MTcwMTIyNjM0MCwicGF0aCI6Ii8xNjIwNzI5Mi8yODY0NTkwNDEtNDAzZWRjZmItY2U3Mi00ODAxLWE2NTQtOWZkMjM3NTljNGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAyNTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZWVlYzI4ZTBlNmYzMjY4MzNiZDNhODgwNjQ3ODU2MWVmNTViYTUzMjZlYmRmMWM1YzNiYzgwNTM3NmMwMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GW2sEpRj7b_jDNMGa5tf66cqKTtaMr_JacLaqPK6_AM)

这种方案应该更合适，直接配置到subfigurecaption里面，@CongzhuoFang 可以参考下
