### ISSUE TITLE
[BUG]Macos系统相关问题

### ISSUE THREAD

**Issue by mwh-aki** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#94]
目前Mcc系统存在以下两个问题，不知如何是好。

问题1:跨平台字体控制部分会报错
\newcommand\defaultSog{SimSun}                              % 宋体，用于正文
\newcommand\defaultHei{SimHei}                              % 黑体，用于标题
\newcommand\defaultKai{KaiTi}                               % 楷体，一般用于强调
\newcommand\defaultFag{FangSong}                            % 仿宋，一般用于强调
目前直接替换为mac对应的postscript虽然可以运行但是不知道会不会产生什么其他的附加问题。

问题2
目前mac运行之后页眉出现问题，本身的页眉应为“第n章 XXXX”，现在页眉实际为“第n章 n.XXXXXX”。
<img width="179" alt="截屏2023-03-14 18 40 57" src="https://user-images.githubusercontent.com/58495023/224975727-749e7f68-de55-46b7-a270-b334f0d1f5d1.png">

**Comment by note286** [comment]
字体问题，可以找有Windows系统的同学拷贝后安装即可。

**Comment by note286** [comment]
页眉问题，Windows 10、TeX Live 2022直接编译`yanputhesis-sample.tex`无任何问题，MacTeX和TeX Live是一样的，macOS和Windows使用LaTeX的差异一般仅在字体配置方面，其他方面都是一致的。

**Comment by polossk** [comment]
字体可替换或按照要求编译
页眉请参考已有issue，是库没有更新导致
https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/issues/51
