### ISSUE TITLE
[Suggestion] 有可能在overleaf上编译吗

### ISSUE THREAD

**Issue by CarlDegio** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#95]
git管理tex总感觉有些麻烦，不知道这个模板有没有可能迁移到overleaf上？

**Comment by polossk** [comment]
> git管理tex总感觉有些麻烦，不知道这个模板有没有可能迁移到overleaf上？

@CarlDegio 您好！如果您时间充裕，可自行同步至 overleaf 上使用。

**Comment by CarlDegio** [comment]
@polossk 想问下字体方面，overleaf找不到宋体等字体，如何解决呢

**Comment by CarlDegio** [comment]
并且还有其他很多报错，可能难度还挺大的。解决了字体问题，又冒出来很多格式问题：
![image](https://user-images.githubusercontent.com/52379582/227699302-60b9ee1a-7474-48cf-bee5-256842e19b7b.png)

**Comment by polossk** [comment]
@CarlDegio 个人感觉不如本地使用，之前也有同学反馈overleaf的连接性不佳，所以这个东西就留给有需要的同学自行处理吧。

**Comment by CarlDegio** [comment]
好，另一方面，可以试试typst。有在线同步，实时渲染的好处。不过目前模板还比较少
